# Generated by Django 5.0.6 on 2024-05-19 19:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0004_homepage_hero_cta_homepage_hero_cta_link_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="homepage",
            name="hero_cta_link",
        ),
        migrations.AddField(
            model_name="homepage",
            name="pdf_link",
            field=models.CharField(
                blank=True,
                help_text="Text to display on Call to Action",
                max_length=255,
                verbose_name="PDF Link",
            ),
        ),
    ]
