# Generated by Django 5.0.6 on 2024-05-19 19:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0005_remove_homepage_hero_cta_link_homepage_pdf_link"),
    ]

    operations = [
        migrations.RenameField(
            model_name="homepage",
            old_name="hero_text",
            new_name="text",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="hero_cta",
        ),
        migrations.AddField(
            model_name="homepage",
            name="link",
            field=models.CharField(
                blank=True, help_text="Link", max_length=255, verbose_name="Link"
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="yt_link",
            field=models.CharField(
                blank=True,
                help_text="Link for YouTube Video to embed",
                max_length=255,
                verbose_name="YouTube Video Link",
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="pdf_link",
            field=models.CharField(
                blank=True,
                help_text="Link for .pdf file to embed",
                max_length=255,
                verbose_name="PDF Link",
            ),
        ),
    ]
