# Generated by Django 4.2.13 on 2024-05-20 13:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0006_rename_hero_text_homepage_text_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="homepage",
            name="image",
        ),
        migrations.AddField(
            model_name="homepage",
            name="image_link",
            field=models.CharField(
                blank=True,
                help_text="Link for Image to embed",
                max_length=255,
                verbose_name="Image Link",
            ),
        ),
    ]
