# Generated by Django 5.0.6 on 2024-05-19 18:40

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NavigationSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "twitter_url",
                    models.URLField(blank=True, verbose_name="Twitter URL"),
                ),
                (
                    "github_url",
                    models.URLField(blank=True, verbose_name="Instagram URL"),
                ),
                (
                    "mastodon_url",
                    models.URLField(blank=True, verbose_name="Facebook URL"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
