# Generated by Django 5.0.6 on 2024-05-19 18:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="navigationsettings",
            old_name="mastodon_url",
            new_name="facebook_url",
        ),
        migrations.RenameField(
            model_name="navigationsettings",
            old_name="github_url",
            new_name="instagram_url",
        ),
    ]
